const AI_PROVIDERS = {
  OPENAI: "openai",
  GEMINI: "gemini",
  OLLAMA: "ollama",
  DEFAULT: "AI",
};

const IPC_CHANNELS = {
  UPDATE_INSTRUCTION: "update-instruction",
  HIDE_INSTRUCTION: "hide-instruction",
  UPDATE_VISIBILITY: "update-visibility",
  TOGGLE_VISIBILITY: "toggle-visibility",
  NOTIFICATION: "notification",
  LOADING: "loading",
  ANALYSIS_RESULT: "analysis-result",
  STREAM_START: "stream-start",
  STREAM_CHUNK: "stream-chunk",
  STREAM_UPDATE: "stream-update",
  STREAM_END: "stream-end",
  CLEAR_RESULT: "clear-result",
  MODEL_CHANGED: "model-changed",
  SCREEN_SHARING_DETECTED: "screen-sharing-detected",
  GET_CURRENT_SETTINGS: "get-current-settings",
  SHOW_CONTEXT_MENU: "show-context-menu",
  TOGGLE_DEVTOOLS: "toggle-devtools",
  UPDATE_MODEL_SETTINGS: "update-model-settings",
  SCREENSHOT_READY_FOR_PROCESSING: "screenshot-ready-for-processing",
  GET_OLLAMA_MODELS: "get-ollama-models",
  DEV_RELOAD: "dev-reload",
  SCROLL_CONTENT: "scroll-content",
  RESIZE_WINDOW: "resize-window",
  MOVE_WINDOW: "move-window",
  QUIT_APP: "quit-app",
  SAVE_API_KEY: "save-api-key",
  GET_API_KEY: "get-api-key",
  INITIALIZE_AI_CLIENT: "initialize-ai-client",
  SEND_CHAT_MESSAGE: "send-chat-message",
  CHAT_MESSAGE_RESPONSE: "chat-message-response",
  CHAT_MESSAGE_STREAM_START: "chat-message-stream-start",
  CHAT_MESSAGE_STREAM_CHUNK: "chat-message-stream-chunk",
  CHAT_MESSAGE_STREAM_END: "chat-message-stream-end",
  TOGGLE_SPLIT_VIEW: "toggle-split-view",
  UPDATE_SYSTEM_PROMPT: "update-system-prompt",
  GET_SYSTEM_PROMPT: "get-system-prompt",
  // Auto Update channels
  UPDATE_STATUS: "update-status",
  CHECK_FOR_UPDATES: "check-for-updates",
  CHECK_FOR_UPDATES_MANUAL: "check-for-updates-manual",
  DOWNLOAD_UPDATE: "download-update",
  INSTALL_UPDATE: "install-update",
  GET_UPDATE_STATUS: "get-update-status",
};

module.exports = {
  AI_PROVIDERS,
  IPC_CHANNELS,
};
